package cn.itcast.bos.dao.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.15
 * 2016-02-22T11:44:22.748+08:00
 * Generated source version: 2.6.15
 * 
 */
@WebService(targetNamespace = "http://ws.itcast.cn/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "operateCustomer", targetNamespace = "http://ws.itcast.cn/", className = "cn.itcast.bos.dao.ws.stub.OperateCustomer")
    @WebMethod
    @ResponseWrapper(localName = "operateCustomerResponse", targetNamespace = "http://ws.itcast.cn/", className = "cn.itcast.bos.dao.ws.stub.OperateCustomerResponse")
    public java.lang.String operateCustomer(
        @WebParam(name = "param", targetNamespace = "")
        java.lang.String param
    );
}
